version: '3'
services:
  app:
    build:
      context: ./ # Dockerfile directory
      dockerfile: Dockerfile # Dockerfile name
    image: go-to-work # image name
    container_name: go-to-work # container name
    ports:
      - 8080:8080
    volumes: # mount workdir
      - ./myapp:/usr/src/app
    command: [sh, -c, npm install && npm start]